runtime: go
api_version: go1
env: flex

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /html
  static_dir: html

- url: /js
  static_dir: js

- url: /profs
  static_dir: profs

- url: /resourses
  static_dir: resourses

- url: /.*
  script: _go_app
